#
# Autogenerated by Thrift Compiler (0.9.1)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
package
	Impala::Protocol::HiveMetastore::Constants;
require 5.6.0;
use strict;
use warnings;
use Thrift;


use constant DDL_TIME => "transient_lastDdlTime";

use constant HIVE_FILTER_FIELD_OWNER => "hive_filter_field_owner__";

use constant HIVE_FILTER_FIELD_PARAMS => "hive_filter_field_params__";

use constant HIVE_FILTER_FIELD_LAST_ACCESS => "hive_filter_field_last_access__";

use constant IS_ARCHIVED => "is_archived";

use constant ORIGINAL_LOCATION => "original_location";

use constant META_TABLE_COLUMNS => "columns";

use constant META_TABLE_COLUMN_TYPES => "columns.types";

use constant BUCKET_FIELD_NAME => "bucket_field_name";

use constant BUCKET_COUNT => "bucket_count";

use constant FIELD_TO_DIMENSION => "field_to_dimension";

use constant META_TABLE_NAME => "name";

use constant META_TABLE_DB => "db";

use constant META_TABLE_LOCATION => "location";

use constant META_TABLE_SERDE => "serde";

use constant META_TABLE_PARTITION_COLUMNS => "partition_columns";

use constant FILE_INPUT_FORMAT => "file.inputformat";

use constant FILE_OUTPUT_FORMAT => "file.outputformat";

use constant META_TABLE_STORAGE => "storage_handler";

1;
